title: 
theme: jekyll-theme-minimal
description: Experimental particle physics researcher. I’m currently a research fellow at the DESY research centre. My main interests concern scientific research and finance.
